package com.gentlemansoftware.pixelworld.inputs;

public enum GamePadButtons {
	
	BACK,START,RIGHTPAD_DOWN,RIGHTPAD_RIGHT,RIGHTPAD_LEFT,RIGHTPAD_UP,SHIFT,CTRL,ESC,LEFTPAD_UP,LEFTPAD_DOWN,LEFTPAD_LEFT,LEFTPAD_RIGHT,LEFTSHOULDER,L2,RIGHTSHOULDER,R2,UNKOWN;
	
}
